"""add invitation links and acceptances

Revision ID: 8460e09ba085
Revises: 0f1351f66ee0
Create Date: 2026-05-06 12:45:38.225786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8460e09ba085'
down_revision: Union[str, Sequence[str], None] = '0f1351f66ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('link_status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.CheckConstraint(
    "link_status IN ('active', 'expired', 'revoked', 'exhausted')",
    name=op.f("ck_invitation_links_status_allowed"),
    ),
    sa.CheckConstraint(
        "current_uses <= max_uses",
        name=op.f("ck_invitation_links_current_uses_lte_max_uses"),
    ),
    sa.CheckConstraint(
        "current_uses >= 0",
        name=op.f("ck_invitation_links_current_uses_non_negative"),
    ),
    sa.CheckConstraint(
        "expires_at > created_at",
        name=op.f("ck_invitation_links_expires_after_created"),
    ),
    sa.CheckConstraint(
        "max_uses IN (1, 5, 10, 25, 50)",
        name=op.f("ck_invitation_links_max_uses_allowed"),
    ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_invitation_links_creator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_invitation_links_revoked_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation_links')),
    sa.UniqueConstraint('token', name=op.f('uq_invitation_links_token'))
    )
    op.create_index('ix_invitation_links_creator_id', 'invitation_links', ['creator_id'], unique=False)
    op.create_index('ix_invitation_links_status_expires_at', 'invitation_links', ['link_status', 'expires_at'], unique=False)
    op.create_table('invitation_acceptances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invitation_link_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('accepted_via', sa.String(length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint(
        "accepted_via IN ('web', 'email', 'link')",
        name=op.f("ck_invitation_acceptances_accepted_via_allowed"),
    ),
    sa.ForeignKeyConstraint(['invitation_link_id'], ['invitation_links.id'], name=op.f('fk_invitation_acceptances_invitation_link_id_invitation_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invitation_acceptances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation_acceptances')),
    sa.UniqueConstraint('invitation_link_id', 'user_id', name='ux_invitation_acceptances_link_user')
    )
    op.create_index('ix_invitation_acceptances_invitation_link_id', 'invitation_acceptances', ['invitation_link_id'], unique=False)
    op.create_index('ix_invitation_acceptances_user_id', 'invitation_acceptances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitation_acceptances_user_id', table_name='invitation_acceptances')
    op.drop_index('ix_invitation_acceptances_invitation_link_id', table_name='invitation_acceptances')
    op.drop_table('invitation_acceptances')
    op.drop_index('ix_invitation_links_status_expires_at', table_name='invitation_links')
    op.drop_index('ix_invitation_links_creator_id', table_name='invitation_links')
    op.drop_table('invitation_links')
    # ### end Alembic commands ###
