"""db(availability-service): init availability tables

Revision ID: 901f5fb17643
Revises: 
Create Date: 2026-01-26 16:22:53.975570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901f5fb17643'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('plan_text', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=5), server_default=sa.text("'es'"), nullable=True),
    sa.Column('is_flexible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("language_code IS NULL OR language_code ~ '^[a-z]{2}(-[A-Z]{2})?$'", name='ck_availabilities_language_code_format'),
    sa.CheckConstraint("source IS NULL OR source IN ('habitual','punctual')", name='ck_availabilities_source'),
    sa.CheckConstraint('start_time_utc < end_time_utc', name='ck_availabilities_start_lt_end'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availabilities_category', 'availabilities', ['category_id'], unique=False)
    op.create_index('idx_availabilities_plan_text', 'availabilities', ['plan_text'], unique=False, postgresql_where=sa.text('plan_text IS NOT NULL'))
    op.create_index('idx_availabilities_source', 'availabilities', ['source'], unique=False, postgresql_where=sa.text('source IS NOT NULL'))
    op.create_index('idx_availabilities_synthetic', 'availabilities', ['is_synthetic'], unique=False)
    op.create_index('idx_availabilities_timerange', 'availabilities', ['start_time_utc', 'end_time_utc'], unique=False)
    op.create_index('idx_availabilities_user_time', 'availabilities', ['user_id', 'start_time_utc', 'end_time_utc'], unique=False)
    op.create_table('availability_day_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('override_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("override_type IN ('replace','clear')", name='ck_availability_day_overrides_override_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='ux_availability_day_overrides_user_date')
    )
    op.create_table('availability_weekly_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_minute', sa.SmallInteger(), nullable=False),
    sa.Column('end_minute', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('plan_text', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=5), server_default=sa.text("'es'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("language_code ~ '^[a-z]{2}(-[A-Z]{2})?$'", name='ck_availability_weekly_templates_language_code_format'),
    sa.CheckConstraint('end_minute BETWEEN 1 AND 1440', name='ck_availability_weekly_templates_end_minute_range'),
    sa.CheckConstraint('start_minute < end_minute', name='ck_availability_weekly_templates_start_lt_end'),
    sa.CheckConstraint('start_minute BETWEEN 0 AND 1439', name='ck_availability_weekly_templates_start_minute_range'),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name='ck_availability_weekly_templates_weekday_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_awd_user', 'availability_weekly_templates', ['user_id'], unique=False)
    op.create_index('idx_awd_user_weekday', 'availability_weekly_templates', ['user_id', 'weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_awd_user_weekday', table_name='availability_weekly_templates')
    op.drop_index('idx_awd_user', table_name='availability_weekly_templates')
    op.drop_table('availability_weekly_templates')
    op.drop_table('availability_day_overrides')
    op.drop_index('idx_availabilities_user_time', table_name='availabilities')
    op.drop_index('idx_availabilities_timerange', table_name='availabilities')
    op.drop_index('idx_availabilities_synthetic', table_name='availabilities')
    op.drop_index('idx_availabilities_source', table_name='availabilities', postgresql_where=sa.text('source IS NOT NULL'))
    op.drop_index('idx_availabilities_plan_text', table_name='availabilities', postgresql_where=sa.text('plan_text IS NOT NULL'))
    op.drop_index('idx_availabilities_category', table_name='availabilities')
    op.drop_table('availabilities')
    # ### end Alembic commands ###
