"""make alias nullable

Revision ID: 012429892e0c
Revises: 25f6c756451c
Create Date: 2025-11-17 13:10:03.053938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012429892e0c'
down_revision: Union[str, Sequence[str], None] = '25f6c756451c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'alias',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'alias',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    # ### end Alembic commands ###
