"""add soft delete fields to users

Revision ID: eeb643c4230e
Revises: 438139e33f04
Create Date: 2025-12-04 18:21:47.751298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb643c4230e'
down_revision: Union[str, Sequence[str], None] = '438139e33f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # 1) Add column nullable=True initially
    op.add_column(
        'users',
        sa.Column('is_deleted', sa.Boolean(), nullable=True)
    )
    
    # 2) Set default value for existing rows
    op.execute("UPDATE users SET is_deleted = FALSE")
    
    # 3) Alter column to NOT NULL
    op.alter_column(
        'users',
        'is_deleted',
        nullable=False
    )
    
    # 4) Add deleted_at normally
    op.add_column(
        'users',
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
